#pragma once


#include "../../FortniteGame/Public/BattleRoyaleGamePhaseLogic.h"
#include "../../FortniteGame/Public/BuildingSMActor.h"
#include "../Public/Configuration.h"
#include <d3d11.h>
#include <fstream>
#include <sstream>

#include <chrono>
#include <iostream>
#include <thread>
#include <io.h>
#include <fcntl.h>

#pragma comment(lib, "d3d11.lib")

inline void DumpItems()
{

    std::stringstream ss;

    ss << "Generated by Boron (Originally: Erbium) (https://github.com/plooshi/Erbium)\n";
    char version[6];

    sprintf_s(version, VersionInfo.FortniteVersion >= 5.00 || VersionInfo.FortniteVersion < 1.2 ? "%.2f" : "%.1f", VersionInfo.FortniteVersion);
    ss << "Fortnite version: " << version << "\n\n";

    auto RarityEnum = EFortRarity::StaticEnum();
    for (int i = 0; i < TUObjectArray::Num(); i++)
    {
        auto Object = TUObjectArray::GetObjectByIndex(i);
        if (!Object || !Object->Class || Object->IsDefaultObject() || !Object->IsA<UFortWorldItemDefinition>())
            continue;
        auto Item = (UFortWorldItemDefinition*)Object;

        FString Name = UKismetTextLibrary::Conv_TextToString(Item->HasDisplayName() ? Item->DisplayName : Item->ItemName);

        ss << "- " << UKismetSystemLibrary::GetPathName(Item).ToString() << "\n";
        ss << "-     Name: " << (Name.GetData() ? Name.ToString() : "None") << "\n";

        auto Names = *(TArray<TPair<FName, int64>>*)(__int64(RarityEnum) + 0x40);

        for (int i = 0; i < Names.Num(); i++)
        {
            auto& Pair = Names[i];
            auto& Name = Pair.Key();
            auto& Value = Pair.Value();

            if (Value == Item->Rarity)
            {
                auto str = Name.ToString();
                auto colcolIdx = str.find_last_of("::");

                auto RealName = colcolIdx == -1 ? str : str.substr(colcolIdx + 1);

                ss << "-     Rarity: " << RealName << "\n";
            }
        }
    }

    std::ofstream of("DumpedItems.txt", std::ios::trunc);

    of << ss.str();
    of.close();
}

inline void DumpPlaylists()
{

    std::stringstream ss;

    ss << "Generated by Boron (Originally: Erbium) (https://github.com/plooshi/Erbium)\n";
    char version[6];

    sprintf_s(version, VersionInfo.FortniteVersion >= 5.00 || VersionInfo.FortniteVersion < 1.2 ? "%.2f" : "%.1f", VersionInfo.FortniteVersion);
    ss << "Fortnite version: " << version << "\n\n";

    auto RarityEnum = EFortRarity::StaticEnum();
    for (int i = 0; i < TUObjectArray::Num(); i++)
    {
        auto Object = TUObjectArray::GetObjectByIndex(i);
        if (!Object || !Object->Class || Object->IsDefaultObject() || !Object->IsA<UFortPlaylistAthena>())
            continue;
        auto Playlist = (UFortPlaylistAthena*)Object;

        FString Name = UKismetTextLibrary::Conv_TextToString(Playlist->UIDisplayName);

        ss << "- " << UKismetSystemLibrary::GetPathName(Playlist).ToString() << "\n";
        ss << "-     Name: " << (Name.GetData() ? Name.ToString() : "None") << "\n";
        if (Playlist->HasMaxPlayers())
            ss << "-     Max players: " << std::to_string(Playlist->MaxPlayers) << "\n";
        if (Playlist->HasMaxSquadSize())
            ss << "-     Squad size: " << std::to_string(Playlist->MaxSquadSize) << "\n";
    }

    std::ofstream of("DumpedPlaylists.txt", std::ios::trunc);

    of << ss.str();
    of.close();
}

inline bool DumpIsCurrent(const char* Path)
{
    std::ifstream In(Path);

    if (!In.good())
        return false;

    std::stringstream Content;
    Content << In.rdbuf();
    auto Text = Content.str();

    char Version[6];
    sprintf_s(Version, VersionInfo.FortniteVersion >= 5.00 || VersionInfo.FortniteVersion < 1.2 ? "%.2f" : "%.1f", VersionInfo.FortniteVersion);

    return Text.find(std::string("Fortnite version: ") + Version + "\n") != std::string::npos && Text.find("\n- ") != std::string::npos;
}

inline void DumpIfNeeded()
{
    auto Start = GetTickCount64();
    bool bItems = !DumpIsCurrent("DumpedItems.txt");
    bool bPlaylists = !DumpIsCurrent("DumpedPlaylists.txt");

    if (bItems)
        DumpItems();

    if (bPlaylists)
        DumpPlaylists();

    printf("[Boron][Dumper] items=%s playlists=%s took=%llums\n", bItems ? "dumped" : "already dumped", bPlaylists ? "dumped" : "already dumped", GetTickCount64() - Start);
}

// here goes sum insaine shit later :))